apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: consumer-keda
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: consumer
  pollingInterval: 5
  cooldownPeriod: 30
  minReplicaCount: 0
  maxReplicaCount: 3
  advanced:
    horizontalPodAutoscalerConfig:
      behavior:
        scaleUp:
          policies:
            - periodSeconds: 5
              type: Pods
              value: 1
          
  triggers:
    - type: rabbitmq
      metadata:
        host: amqp://user:2zcB2936e3m4Lt3f@10.103.205.198:5672/vhost
        protocol: auto
        vhostName: /
        mode: QueueLength
        value: "3000"
        queueName: super_duper_queue