apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: consumer-keda
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: consumer
  pollingInterval: 5
  cooldownPeriod: 10
  minReplicaCount: 0
  maxReplicaCount: 10
  advanced:
    horizontalPodAutoscalerConfig:
      behavior:
        scaleUp:
          stabilizationWindowSeconds: 0
          policies:
            - periodSeconds: 1
              type: Percent
              value: 100
        scaleDown:
          stabilizationWindowSeconds: 0
          selectPolicy: Max # scale base on max value in range, Default is Max
          policies:
            - periodSeconds: 1
              type: Percent
              value: 100

  triggers:
    - type: rabbitmq
      metadata:
        host: amqp://user:MjKhazDTPw8PREaS@10.110.241.12:5672/vhost
        protocol: auto
        vhostName: /
        mode: QueueLength
        value: "10000"
        queueName: super_duper_queue
